export const TOGGLE_NAVIGATION_OPEN = 'TOGGLE_NAVIGATION_OPEN';
export const TOGGLE_OPTION_DROPDOWN_OPEN = 'TOGGLE_OPTION_DROPDOWN_OPEN';
export const TOGGLE_SUCCESS_MESSAGE_ON = 'TOGGLE_SUCCESS_MESSAGE_ON';
