
export const FETCH_PRODUCTS =  'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_BY_CATEGORY = "FETCH_PRODUCTS_BY_CATEGORY";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";